name: algolia-scraper

on:
  workflow_run:
    workflows: ['Publish Image']
    types:
      - completed

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      ALGOLIA_APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
      ALGOLIA_WRITE_API_KEY: ${{ secrets.ALGOLIA_ADMIN_API_KEY }}
      ALGOLIA_SITE_URL: ${{ secrets.ALGOLIA_SITE_URL }}
      ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}
    steps:
      - name: check out code 🛎
        uses: actions/checkout@v2

      - name: clear algolia index 🧽
        run: |
          cd .algolia
          pip install --upgrade 'algoliasearch>=2.0,<3.0'
          python clear_index.py

      - name: scrape the site 🧽
        run: |
          cd .algolia
          touch .env
          sudo chmod +x ./scraper.sh
          ./scraper.sh
